services:

  webapp: 
    image: !reset
    build:
      context: ../webapp/
      target: dev
      additional_contexts:
        - shared=../shared/
    volumes:
      - ../webapp/:/srv/sonddr/
    restart: !reset

  api:
    image: !reset
    build: 
      context: ../api/
      additional_contexts:
        - shared=../shared/
    restart: !reset

  sessions-database:
    restart: !reset

  auth: 
    image: !reset
    build:
      context: ../auth/
      target: dev
    restart: !reset

  auth-database:
    restart: !reset

  database:
    image: !reset
    build: ../database/
    restart: !reset

  reverse-proxy:
    image: !reset
    build: 
      context: ../reverse-proxy/
    volumes:
      - ./letsencrypt:/etc/letsencrypt/
    restart: !reset
