global:

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /monitoring/database/metrics
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'cadvisor'
    metrics_path: /metrics
    static_configs:
      - targets: ['docker-scraper:8080']
