db = connect('mongodb://localhost/sonddr')
db.createCollection("goals", { changeStreamPreAndPostImages: { enabled: true} })
db.createCollection("cheers", { changeStreamPreAndPostImages: { enabled: true} })
db.createCollection("comments", { changeStreamPreAndPostImages: { enabled: true} })
db.createCollection("ideas", { changeStreamPreAndPostImages: { enabled: true} })
db.createCollection("users", { changeStreamPreAndPostImages: { enabled: true} })
db.createCollection("votes", { changeStreamPreAndPostImages: { enabled: true} })
db.createCollection("messages", { changeStreamPreAndPostImages: { enabled: true} })
db.createCollection("discussions", { changeStreamPreAndPostImages: { enabled: true} })
db.createCollection("notifications", { changeStreamPreAndPostImages: { enabled: true} })
db.createCollection("volunteers", { changeStreamPreAndPostImages: { enabled: true} })
db.createCollection("drafts", { changeStreamPreAndPostImages: { enabled: true} })
db.createCollection("push", { changeStreamPreAndPostImages: { enabled: true} })
