on:
  push:
    branches:
      - master

jobs:
  pull_and_reinit:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script_stop: true
          script: |
            cd /srv/sonddr
            git pull --recurse-submodules
            git submodule update --recursive
            sudo -E ./devctl.sh reinit api  # need env
            sudo -E ./devctl.sh reinit webapp
